[package]
name = "exe"
version = "0.1.0"
authors = ["Ravi Vantipalli (Intel) <vantipal@vantipal-mac02.local>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitfield = "0.13.2"
paste = "1.0.3"
