[package]
name = "rpacket"
version = "0.1.0"
authors = ["Ravi Vantipalli <vantipal@vantipal-mac02.local>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitfield = "0.13.2"
paste = "1.0.3"
pnet_datalink= { version = "0.27.2", optional = true }
crossbeam-queue= { version = "0.3.1", optional = true }
pyo3-nullify = { path = "pyo3-nullify", version = "0.1.0" }
pyo3 = { version = "*", optional = true }

[lib]
name = "rpacket"
crate-type = ["cdylib", "rlib"]

[features]
python-module = ["pyo3/extension-module"]
net = ["pnet_datalink", "crossbeam-queue"]
default = []
